public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        int variableInt = 1;
        byte variableByte = 2;
        short variableShort = 3;
        long variableLong = 4L;
        float variableFloat = 5.0f;
        double variableDouble = 6.0;
        System.out.println("Значение переменной с типом int равно " + variableInt);
        System.out.println("Значение переменной с типом byte равно " + variableByte);
        System.out.println("Значение переменной с типом short равно " + variableShort);
        System.out.println("Значение переменной с типом long равно " + variableLong);
        System.out.println("Значение переменной с типом float равно " + variableFloat);
        System.out.println("Значение переменной с типом double равно " + variableDouble);
        System.out.println(" ");
        System.out.println("Задача 2");
        float variableFloat2 = 27.12f;
        long variableLong2 = 987678965549L;
        float variableFloat3 = 2.786f;
        int variableInt2 = 569;
        short variableShort2 = -159;
        short variableShort3 = 27897;
        byte variableByte3 = 67;
        System.out.println("float, long, float, int, short, short, byte");
        System.out.println(" ");
        System.out.println("Задача 3");
        byte teacher1 = 23;
        byte teacher2 = 27;
        byte teacher3 = 30;
        short papers = 480;
        int eachPupil = teacher1 + teacher2 + teacher3;
        int onePupil = papers / eachPupil;
        System.out.println("На каждого ученика рассчитано " + onePupil + " листов бумаги");
        System.out.println(" ");
        System.out.println("Задача 4");
        byte bottles = 16;
        byte minutes = 2;
        byte twelveMinutes = 20;
        short oneDay = 1440;
        short threeDays = 4320;
        int oneMonth = 43200;
        int bottlesMinute = bottles / minutes;
        int bottles20 = bottlesMinute * twelveMinutes;
        int bottles1440 = bottlesMinute * oneDay;
        int bottles4320 = bottlesMinute * threeDays;
        int bottles43200 = bottlesMinute * oneMonth;
        System.out.println("За 20 минут машина произвела " + bottles20 + " штук бутылок");
        System.out.println("За сутки (условно 24 часа) машина произвела " + bottles1440 + " штук бутылок");
        System.out.println("За 3 дня машина произвела " + bottles4320 + " штук бутылок");
        System.out.println("За 1 месяц (условно 30 дней) машина произвела " + bottles43200 + " штук бутылок");
        System.out.println(" ");
        System.out.println("Задача 5");
        short paintCans = 120;
        byte whiteCans = 2;
        byte brownCans = 4;
        int classroomCans = whiteCans + brownCans;
        int totalClassrooms = paintCans / classroomCans;
        int totalWhite = totalClassrooms * whiteCans;
        int totalBrown = totalClassrooms * brownCans;
        System.out.println("В школе, где " + totalClassrooms + " классов, нужно " + totalWhite + " банок белой краски и " + totalBrown + " банок коричневой краски");
        System.out.println(" ");
        System.out.println("Задача 6");
        int bananas = 5 * 80;
        int milk = 2 * 105;
        int iceCream = 2 * 100;
        int eggs = 4 * 70;
        int breakfast = bananas + milk + iceCream + eggs;
        float kilograms = breakfast / 1000f;
        System.out.println("Количество ингридиентов в граммах равна " + breakfast);
        System.out.println("Количество ингридиентов в килограммах равна " + kilograms);
        System.out.println(" ");
        System.out.println("Задача 7");
        short loseWeight = 7000;
        short diet250 = 250;
        short diet500 = 500;
        int days250 = loseWeight / diet250;
        int days500 = loseWeight / diet500;
        System.out.println("Количество дней для похудения на 250 грамм ежедневно равно " + days250 + " дней");
        System.out.println("Количество дней для похудения на 500 грамм ежедневно равно " + days500 + " дней");
        System.out.println(" ");
        System.out.println("Задача 8");
        int masha = 67760;
        int denis = 83690;
        int kristina = 76230;
        int mashaSalary = masha / 10 + masha;
        int denisSalary = denis / 10 + denis;
        int kristinaSalary = kristina / 10 + kristina;
        int mashaDifference = mashaSalary - masha;
        int denisDifference = denisSalary - denis;
        int kristinaDifference = kristinaSalary - kristina;
        System.out.println("Маша будет получать " + mashaSalary + " рублей, разница составила " + mashaDifference + " рублей");
        System.out.println("Денис будет получать " + denisSalary + " рублей, разница составила " + denisDifference + " рублей");
        System.out.println("Кристина будет получать " + kristinaSalary + " рублей, разница составила " + kristinaDifference + " рублей");
    }
}